version: '3.8'

services:
    backend:
        build:
            context: ./recommender-be
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        environment:
            - CORS_ORIGINS=http://localhost:3000 # Allow frontend to connect when running locally
